import { Shield, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border/40 bg-background/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="container flex items-center justify-between h-16">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-violet-500/20 border border-violet-500/30 flex items-center justify-center">
              <Shield className="w-4 h-4 text-violet-400" />
            </div>
            <span className="font-bold text-lg tracking-tight">PhishSim AI</span>
          </div>
          <Button variant="ghost" size="sm" onClick={() => window.location.href = "/"}>
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to Home
          </Button>
        </div>
      </header>
      <main className="container max-w-3xl py-16">
        <h1 className="text-4xl font-black mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-10">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="space-y-8 text-sm text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using the PhishSim AI platform ("Service") at www.phishsimai.com, you agree to be bound by these Terms of Service ("Terms"). If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">2. Description of Service</h2>
            <p>PhishSim AI provides a cloud-based security awareness training and phishing simulation platform. The Service allows organizations to send simulated phishing emails to their own employees, track responses, deliver training content, and generate compliance documentation. The Service is intended solely for authorized security awareness programs conducted by organizations against their own employees with appropriate disclosure.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">3. Authorized Use Only</h2>
            <p className="mb-3">You agree that you will only use the Service to conduct phishing simulations against individuals who are: (a) employees, contractors, or members of your own organization; and (b) subject to an acceptable use policy or employment agreement that permits security testing.</p>
            <p><strong className="text-foreground">You expressly agree NOT to use the Service to:</strong> send phishing simulations to individuals outside your organization; conduct unauthorized security testing; harvest real credentials; engage in any activity that violates applicable law; or impersonate any person or entity for malicious purposes. Violation of this section will result in immediate account termination and may result in legal action.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">4. Subscription and Payment</h2>
            <p>Access to the Service requires a paid subscription after the 14-day free trial period. Subscription fees are billed monthly or annually in advance. All fees are non-refundable except as required by law. We reserve the right to modify pricing with 30 days' notice. Failure to pay may result in suspension or termination of your account.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">5. Compliance Documentation</h2>
            <p>Compliance reports and certificates generated by the Service are provided as documentation aids only. PhishSim AI does not guarantee that use of the Service will result in compliance with any specific regulation. You are solely responsible for ensuring your organization meets all applicable legal and regulatory requirements. We recommend consulting qualified legal and compliance counsel for your specific situation.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">6. MSP and Reseller Terms</h2>
            <p>Managed Service Providers (MSPs) using the white-label portal agree to: (a) only provision the Service for their legitimate end-customer organizations; (b) ensure each end-customer agrees to these Terms before accessing the Service; (c) maintain appropriate agreements with their customers governing the use of phishing simulation services; and (d) be jointly and severally liable for their customers' compliance with these Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">7. Intellectual Property</h2>
            <p>The Service, including all software, AI models, templates, training content, and documentation, is owned by PhishSim AI and protected by intellectual property laws. You are granted a limited, non-exclusive, non-transferable license to use the Service during your subscription term. You retain ownership of your organization's data uploaded to the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">8. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, PHISHSIM AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT PAID BY YOU FOR THE SERVICE IN THE TWELVE MONTHS PRECEDING THE CLAIM.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">9. Termination</h2>
            <p>Either party may terminate these Terms at any time. Upon termination, your access to the Service will cease and your data will be deleted within 90 days. We may terminate your account immediately for violation of these Terms, particularly Section 3 (Authorized Use Only).</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">10. Governing Law</h2>
            <p>These Terms shall be governed by the laws of the State of Maryland, without regard to its conflict of law provisions. Any disputes shall be resolved in the state or federal courts located in Maryland.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">11. Contact</h2>
            <p>Questions about these Terms should be directed to:<br />
            <strong className="text-foreground">PhishSim AI</strong><br />
            Email: legal@phishsimai.com<br />
            Phone: 443-594-1184<br />
            Website: www.phishsimai.com</p>
          </section>
        </div>
      </main>
    </div>
  );
}
