// ─────────────────────────────────────────────────────────────────────────────
//  PS-WHITELABEL-CERT-01 — the cert carries the reseller's brand, never the truth.
//
//  An MSP reselling PhishSim hands a compliance cert to their client; it must show the MSP's name,
//  not their vendor's. White-labeling the BRAND must not white-label the FACTS: rates, counts, and
//  the attestation stay real regardless of whose logo is on the page.
//
//  PDF text is glyph-split and compressed, so this verifies at the SOURCE + LOGIC level (which
//  strings are brand-tokenised vs. factual) and proves the brand flows through by byte-difference —
//  a branded cert and a default cert are not the same bytes.
// ─────────────────────────────────────────────────────────────────────────────
import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import { generateInsurancePack } from './insurancePack'

const SRC = fs.readFileSync('server/reports/insurancePack.ts', 'utf8')
const facts = {
  orgName: 'Northwind Clinic',
  campaigns: [{ name: 'Q1', createdAt: new Date('2026-03-01'), targetCount: 40, clickRate: 12, reportRate: 55 }],
  totalEmployeesTrained: 40, baselineClickRate: 22, currentClickRate: 12,
  trainingModulesCount: 20, reportPeriodStart: new Date('2025-08-01'), reportPeriodEnd: new Date('2026-08-01'),
}

describe('the brand is a token with an honest fallback', () => {
  it('falls back to "PhishSim AI" ONLY when brandName is unset', () => {
    expect(SRC).toContain('const brand = (params.brandName || "").trim() || "PhishSim AI"')
  })

  it('every brand stamp renders ${brand}, not a hardcoded "PhishSim AI"', () => {
    // The 6 attribution spots must all interpolate brand. A bare doc.text("...PhishSim AI...") would
    // hardcode our name onto a reseller's cert.
    const docTextWithLiteral = [...SRC.matchAll(/doc[^\n]*?text\([^\n]*PhishSim AI[^\n]*\)/g)]
    expect(docTextWithLiteral, 'a doc.text still hardcodes "PhishSim AI"').toEqual([])
  })

  it('${brand} appears in the prepared-by, provenance, attestation and footer', () => {
    expect(SRC).toContain('Prepared by: ${brand}')
    expect(SRC).toContain('verified by ${brand} platform data')
    expect(SRC).toContain('program through ${brand}')
    expect(SRC).toContain('generated by ${brand}')
    expect(SRC).toContain('${brand} — Cyber Insurance Readiness Pack')
  })

  it("the ™ is shown only for PhishSim's own brand, never claimed for a reseller", () => {
    expect(SRC).toContain('isDefaultBrand ? "Readiness Pack\\u2122" : "Readiness Pack"')
  })
})

describe('white-labeling the brand does NOT white-label the truth', () => {
  it('the factual claims are literal in source — not brand-tokenised, not removed', () => {
    // These are the TRUTH the cert asserts; they must survive any rebrand verbatim.
    expect(SRC).toContain('represents actual platform activity')
    expect(SRC).toContain('available for carrier verification upon request')
    expect(SRC).toContain('demonstrating a ${improvement} percentage-point risk reduction')
    expect(SRC).toContain('${campaigns.length} phishing simulation campaign(s) covering ${totalEmployeesTrained} employees')
    // The subject org (the client being certified) is always its real name.
    expect(SRC).toContain('doc.fillColor(NAVY).fontSize(22).font("Helvetica-Bold").text(orgName')
  })
})

describe('the brand actually flows through to the output', () => {
  it('a rebranded cert and a default cert are different bytes', async () => {
    const rebranded = await generateInsurancePack({ ...facts, brandName: 'Acme MSP Security', logoUrl: null })
    const vendor = await generateInsurancePack({ ...facts, brandName: null, logoUrl: null })
    expect(rebranded.length).toBeGreaterThan(1000)
    expect(vendor.length).toBeGreaterThan(1000)
    expect(rebranded.slice(0, 5).toString()).toBe('%PDF-') // valid PDF
    // If brand did not flow through, these would be byte-identical.
    expect(Buffer.compare(rebranded, vendor)).not.toBe(0)
  })

  it('a broken/missing logo never throws — the cert still generates', async () => {
    const buf = await generateInsurancePack({ ...facts, brandName: 'Acme MSP', logoUrl: 'https://nonexistent.invalid/logo.png' })
    expect(buf.slice(0, 5).toString()).toBe('%PDF-')
  })
})
